functionsDirectory = "/Users/munirkabir/Desktop/ShegerPay/cinema-cafe-menu/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/munirkabir/Desktop/ShegerPay/cinema-cafe-menu/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/munirkabir/Desktop/ShegerPay/cinema-cafe-menu/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]